### ISSUE TITLE
Configure drawer menu slide width, instead of the right maring

### ISSUE THREAD

**Issue by AlexNab** [EddieRingle/android-undergarment#3] opened 2012-10-03 20:04 UTC
Actual state of Undergarment drawer menu slides drawer menu always to the right edge of the screen with respect of the little margin (48dp, not configurable).

While for narrow screens it's ok, for wide screens (phones in landscape orientations, tablets) - this becomes not so good. Drawer menu usually doesn't require so much space. 

So I suggest to make drawer menu width configurable. This will be more convenient that configurable margin.

**Comment by EddieRingle** [comment] 2012-10-28 19:07
Duplicate of #2.

**Closed as completed by EddieRingle** 2012-10-28 19:07 UTC
Labels: duplicate
